### ISSUE TITLE
no readme

### ISSUE THREAD

**Issue by KristerV** [stevezhu/meteor-fbgraph#2]
I would rather use your package instead of https://atmospherejs.com/dcsan/facebook-sdk just because it has been updated more recently, but the absence of insctructions just makes this package useless. Yeah, I can read the node instructions, but what applies to meteor and what doesn't? Am i supposed to go read you source or what?

**Comment by stevezhu** [comment]
Sorry, when I made this package it was meant for personal use. Updated the readme.  
To summarize, you just use `FBGraph` instead of `graph` as noted in the node [fbgraph](http://criso.github.io/fbgraph/) package.

**Comment by KristerV** [comment]
ah, nice. thanks! Clears up a lot.
